###############################################################################
# Sloan Digital Sky Survey III (SDSS-III)
###############################################################################

SHELL = /bin/sh
#
all :;

install :
	- cp bbspec.table $(IDLSPEC2D_DIR)/ups
	- cp Makefile $(IDLSPEC2D_DIR)/ups

clean :
	rm -f *~ core *.bak *.orig *.old .#* #*#
